name: Automated Testing

on:
  push:
    branches:
      - "dev"

jobs:
  test-ecnuthesis:
    strategy:
      matrix:
        include:
        - runs-on: ubuntu-latest
          shell: bash
          tl-pkgs: ""
        - runs-on: macos-latest
          shell: bash
          tl-pkgs: ""
        - runs-on: windows-latest
          shell: pwsh
          tl-pkgs: wintools.windows
          
    name: on ${{ matrix.runs-on }}

    runs-on: ${{ matrix.runs-on }}

    defaults:
      run:
        shell: ${{ matrix.shell }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v6

    - name: Install TeX Live
      uses: zauguin/install-texlive@v4
      with:
        package_file: .github/tl_packages
        packages: ${{ matrix.tl-pkgs }}

    - name: Check ecnuthesis
      id: test
      run: |
        l3build check -q -H
      env:
        diffext: .diff
        diffexe: git diff --no-index --text --

    - name: Get short commit SHA
      if: ${{ !cancelled() && steps.test.outcome == 'failure' }}
      run: |
        echo "SHA_SHORT=$(git rev-parse --short=8 HEAD)" >> $GITHUB_ENV

    - name: Upload test diffs
      if: ${{ !cancelled() && steps.test.outcome == 'failure' }}
      uses: actions/upload-artifact@v6
      with:
        name: ecnuthesis-diff-${{ env.SHA_SHORT }}-${{ runner.os }}
        path: |
          build/**/*.diff